name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Restore .NET dependencies
      run: dotnet restore
    - name: Build .NET
      run: dotnet build --no-restore --output ./artifacts --configuration Release
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ./artifacts
